### ISSUE TITLE
Trying to withdraw less than a dollar. 

### ISSUE THREAD

**Issue by losc3571** [soga2001/FinalProject#1]
This isn't necessarily and error I just wanted to note that you must withdraw in dollar increments, you can't use cents. If this is intended then ignore this I just wasn't sure.

**Comment by soga2001** [comment]
Yea that is how it is supposed to be

**Comment by soga2001** [comment]
Because I need to use a function to check whether the input is a number or not and it doesn't take decimal as a number. Also without this function, if I input anything other than a number, it goes into an infinite loop.
