### ISSUE TITLE
Password when closing account. 

### ISSUE THREAD

**Issue by losc3571** [soga2001/FinalProject#2]
When I select the option to close the account it prompts me to enter the password. The account says it is closed whether I enter the correct password or not.

**Comment by soga2001** [comment]
Hi, Did you ever check if the account was actually ever deleted? Because I am also running into a problem right now where the account didn't get deleted.

**Comment by losc3571** [comment]
No I did not. I just noticed that it displayed the account deleted message. I'm not sure about the account actually being deleted in the data structure itself.

**Comment by soga2001** [comment]
Oh okay, yea I fixed the problem with closing an account just now. It doesn’t work well with chaining but I am still trying to figure it out.
